@url = http://localhost:8080/api/message/like

// get all likes
GET {{url}} HTTP/1.1

###

GET {{url}}/id/3 HTTP/1.1

###

// get likes by userId
GET {{url}}/user/4 HTTP/1.1

###

// get likes by messageId
GET {{url}}/3 HTTP/1.1

###

// add a like
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "isliked": false,
    "userId": 4,
    "messageId": 1
}

###

// update a like
PUT {{url}}/id/10 HTTP/1.1
Content-Type: application/json

{
    "likeId": 10,
    "userId": 4,
    "messageId": 1,
    "liked": true
}

###

// delete a like
DELETE {{url}}/id/5 HTTP/1.1
